M48
; DRILL file {KiCad 8.0.3-8.0.3-0~ubuntu22.04.1} date 2024-06-18T13:07:57+0300
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-06-18T13:07:57+03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.3-8.0.3-0~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.200
%
G90
G05
T1
X52.0Y-34.0
X52.0Y-67.75
X95.0Y-34.0
X95.0Y-67.75
M30
